### ISSUE TITLE
How can i use this in my java project

### ISSUE THREAD

**Issue by crustycrabthe3rd** [nathanielove/Java-Console-View#1]
I'm still new to java and i'm executing my simple programs in the command prompt on windows.
How do i use this framework in my case.
Do i have to copy the .java files somewhere?
Do i have to use "import"?
Thank you :)

**Comment by thousandlemons** [comment]
Sorry I replied the email but Idk why it doesn't show here.

I’m pretty willing to help you setup the project step by step, if necessary. 

But first, the easiest way to install this package is to use Maven. Can you do a little bit research on Maven first? Also can I get to know what IDE you are using?

**Comment by nathanielove** [comment]
Hi,

I’m pretty willing to help you setup the project step by step.

The easiest way to install this package is to use Maven. Can you do a little bit research on Maven first? Also can I get to know what IDE you are using?

Best regards

Nathaniel Sun

**Comment by crustycrabthe3rd** [comment]
Thank you for trying to help Nathan :)
I have Intellij Idea, and Eclipse, but i don't really use them yet. Although, i have checked out maven and followed the installation steps and i installed it on Intellij Idea. What do i do now?

**Comment by thousandlemons** [comment]
With your IntellijIDEA:
1. File -> New -> New Project
2. Select "Maven" in the list, then click "Next"
3. In the next page, fill in "Group ID" (e.g. "com.example") and "Artifact ID" (e.g. "my-sample-project"), and click "Next"
4. In the next page, fill in your project name and click "Finish"

After all these, you'll see a `pom.xml` in your project directory. Double click to open that file.

Inside of the `<project>` tag, see if you have an `<dependencies>` tag. If you DO, add the following block inside of your `<dependencies>` tag:

``` xml
<dependency>
  <groupId>io.bretty</groupId>
  <artifactId>console-view</artifactId>
  <version>3.4</version>
</dependency>
```

If you DON'T, add the following block inside of your `<project>` tag:

``` xml
<dependencies>
  <dependency>
    <groupId>io.bretty</groupId>
    <artifactId>console-view</artifactId>
    <version>3.4</version>
  </dependency>
</dependencies>
```

Then, there will be a pop up in Intellij asking you if you wanna turn on auto import for this project. Click "Enable Auto-import" and let Intellij do all the download and installation.

After it's done, you can now create your own packages and classes, and import whatever you need from this library.

**Comment by crustycrabthe3rd** [comment]
Thank you so much, I will try that now!
